# have to use trusty because xenial is broken
sudo: false
language: perl
perl:
   - 'blead'
   - '5.30'
   - '5.28'
   - '5.26'
   - '5.24'
   - '5.22'
matrix:
  fast_finish: true
  allow_failures:
    - perl: 'blead'
    - perl: '5.8'
  include:
    - perl: '5.20'
      dist: trusty
    - perl: '5.18'
      dist: trusty
    - perl: '5.16'
      dist: trusty
    - perl: '5.14'
      dist: trusty
    - perl: '5.12'
      dist: trusty
    - perl: '5.10'
      dist: trusty
    - perl: '5.8'
      dist: trusty
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla
   - "dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest"
   - "dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose"
script:
   - dzil smoke --release --author
